### ISSUE TITLE
mysql dump

### ISSUE THREAD

**Issue by yjradeh** [easy-cloud/EasyACL#2]
Can you please provide us with the default mysql dump for testing this project?

**Comment by TNAJanssen** [comment]
Sure thing, i will upload it today.

**Comment by yjradeh** [comment]
Wawww! thank you

**Comment by TNAJanssen** [comment]
https://raw.github.com/easy-cloud/acl/master/README.md

You need to update first!

You can find everything you need in there!

Can you test it for me if it works, you get the password and can login after you add the user and role?

**Comment by TNAJanssen** [comment]
Did you figure it out?

**Comment by IgorDePaula** [comment]
No, you don't upload the mysql dump, upload please.

**Comment by TNAJanssen** [comment]
You don't need an MySQL dump! because you have to import the database through doctrine 2!

**Comment by IgorDePaula** [comment]
ok, i created a code that generate the mysql structure, thanks

**Comment by TNAJanssen** [comment]
Great, if you have any questions feel free to ask me.
